#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build raya/regression/fleet.json — the machine-readable fleet the tooling reads.

Why this exists: the daily static suite used to hard-code its own file list, which silently
omitted two LIVE bots (dkb-hi-in, dkb-kn-in) for days while the digest reported "16 bots checked"
as if that were the whole fleet. Hand-maintained fleet lists rot. This derives the manifest from
the two things that are already authoritative:

  * raya/agents.json                      — the deploy manifest (which bots exist, live uuids)
  * raya/regression/static_regression.py  — discover_prompts(), the label/role/backend derivation

and cross-checks them against each other, so a bot can never be in one and missing from the other
without someone being told.

Usage:
  python3 scripts/build_fleet_manifest.py            # write raya/regression/fleet.json
  python3 scripts/build_fleet_manifest.py --check    # exit 1 if the file is missing/stale (CI-safe)
  python3 scripts/build_fleet_manifest.py --print    # dump to stdout, write nothing
"""
import json, os, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "raya", "regression"))
OUT = os.path.join(REPO, "raya", "regression", "fleet.json")

# Which project a bot folder belongs to. Extend when a new project is registered — a bot whose
# folder is not listed lands in "unassigned" and is reported, never silently dropped.
PROJECTS = {
    "KKB": "blue-dots",
    "DKB": "blue-dots",
    "Maya": "blue-dots",
}


def load_agents():
    p = os.path.join(REPO, "raya", "agents.json")
    d = json.load(open(p, encoding="utf-8"))
    targets = d["targets"] if isinstance(d, dict) and "targets" in d else d
    return [t for t in targets if t.get("kind") == "conversation"]


def build():
    from static_regression import discover_prompts  # reuse the ONE derivation of label/role/backend

    prompts = {p["path"]: p for p in discover_prompts()}
    targets = load_agents()

    entries, problems = [], []
    for t in targets:
        f = t.get("file")
        p = prompts.get(f)
        if p is None:
            problems.append(f"live target '{t.get('id')}' -> '{f}' is NOT covered by the daily "
                            f"suite's discover_prompts()")
            continue
        project = PROJECTS.get(p["agent"], "unassigned")
        if project == "unassigned":
            problems.append(f"bot folder '{p['agent']}' has no project mapping in PROJECTS")
        entries.append({
            "bot_id": t.get("id"),
            "label": p["bot"],                       # "<Agent> <Language> · <direction> · <backend>"
            "blurb": p["blurb"],
            "file": f,
            "project": project,
            "agent": p["agent"],
            "language": p["lang"],
            "direction": p["direction"],
            "backend": p["backend"],
            "role": "seeker" if p["seeker"] else "provider",
            # bots that must stay in sync with each other = same agent+direction+backend, N languages
            "sync_group": f"{p['agent']}:{p['direction']}:{p['backend']}",
            "deploy": bool(t.get("deploy")),
        })

    # the reverse direction: a prompt the suite checks that no live target claims
    for path in sorted(set(prompts) - {t.get("file") for t in targets}):
        problems.append(f"suite checks '{path}' but no conversation target in agents.json owns it")

    # master language per sync group: the group's Hindi file if present, else the first alphabetically.
    groups = {}
    for e in entries:
        groups.setdefault(e["sync_group"], []).append(e)
    for g, members in groups.items():
        langs = sorted({m["language"] for m in members})
        master = "hi" if "hi" in langs else langs[0]
        for m in members:
            m["sync_group_languages"] = langs
            m["master_language"] = master

    return {
        "_note": ("GENERATED by scripts/build_fleet_manifest.py — do not hand-edit. Re-run after "
                  "registering a bot or adding a language. Derived from raya/agents.json (deploy "
                  "manifest) + static_regression.discover_prompts()."),
        "generated_from": ["raya/agents.json", "raya/regression/static_regression.py"],
        "bot_count": len(entries),
        "projects": sorted({e["project"] for e in entries}),
        "bots": sorted(entries, key=lambda e: (e["project"], e["agent"], e["direction"], e["language"])),
    }, problems


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "--write"
    manifest, problems = build()
    text = json.dumps(manifest, ensure_ascii=False, indent=1) + "\n"

    for p in problems:
        print(f"WARNING: {p}", file=sys.stderr)

    if mode == "--print":
        sys.stdout.write(text)
        return 1 if problems else 0

    if mode == "--check":
        if not os.path.exists(OUT):
            print(f"fleet.json missing — run: python3 scripts/build_fleet_manifest.py", file=sys.stderr)
            return 1
        current = open(OUT, encoding="utf-8").read()
        if current != text:
            print("fleet.json is STALE — re-run: python3 scripts/build_fleet_manifest.py", file=sys.stderr)
            return 1
        print(f"fleet.json current ({manifest['bot_count']} bots)")
        return 1 if problems else 0

    open(OUT, "w", encoding="utf-8").write(text)
    print(f"wrote raya/regression/fleet.json — {manifest['bot_count']} bots across "
          f"{len(manifest['projects'])} project(s): {', '.join(manifest['projects'])}")
    if problems:
        print(f"  ({len(problems)} warning(s) above — fix them or the fleet is incomplete)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
